//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagar_Shrushti.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sagar_Shrushti.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _2bedroom {
            get {
                object obj = ResourceManager.GetObject("_2bedroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4bedroom {
            get {
                object obj = ResourceManager.GetObject("_4bedroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap accordionHeader1 {
            get {
                object obj = ResourceManager.GetObject("accordionHeader1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap accordionHeader2 {
            get {
                object obj = ResourceManager.GetObject("accordionHeader2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alibaug_fort {
            get {
                object obj = ResourceManager.GetObject("alibaug_fort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap betelnut_bullet {
            get {
                object obj = ResourceManager.GetObject("betelnut_bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap betelnut_bullet2 {
            get {
                object obj = ResourceManager.GetObject("betelnut_bullet2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap betelnut_bullet3 {
            get {
                object obj = ResourceManager.GetObject("betelnut_bullet3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap beverages {
            get {
                object obj = ResourceManager.GetObject("beverages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap birla_mandir {
            get {
                object obj = ResourceManager.GetObject("birla_mandir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Boat {
            get {
                object obj = ResourceManager.GetObject("Boat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bottombar {
            get {
                object obj = ResourceManager.GetObject("bottombar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakfast {
            get {
                object obj = ResourceManager.GetObject("breakfast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chicken {
            get {
                object obj = ResourceManager.GetObject("chicken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_icon {
            get {
                object obj = ResourceManager.GetObject("close_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contentBackground {
            get {
                object obj = ResourceManager.GetObject("contentBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap datta_mandir {
            get {
                object obj = ResourceManager.GetObject("datta_mandir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01249 {
            get {
                object obj = ResourceManager.GetObject("DSC01249", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01249small {
            get {
                object obj = ResourceManager.GetObject("DSC01249small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01256 {
            get {
                object obj = ResourceManager.GetObject("DSC01256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01256small {
            get {
                object obj = ResourceManager.GetObject("DSC01256small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01258 {
            get {
                object obj = ResourceManager.GetObject("DSC01258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01258small {
            get {
                object obj = ResourceManager.GetObject("DSC01258small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01261 {
            get {
                object obj = ResourceManager.GetObject("DSC01261", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DSC01261small {
            get {
                object obj = ResourceManager.GetObject("DSC01261small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facilitesImage {
            get {
                object obj = ResourceManager.GetObject("facilitesImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Script by: www.jtricks.com
        /// * Version: 1.5 (20110204)
        /// * Latest version: www.jtricks.com/javascript/navigation/floating.html
        /// */
        ///var floatingMenu =
        ///{
        ///    hasInner: typeof(window.innerWidth) == &apos;number&apos;,
        ///    hasElement: typeof(document.documentElement) == &apos;object&apos;
        ///        &amp;&amp; typeof(document.documentElement.clientWidth) == &apos;number&apos;
        ///};
        ///
        ///var floatingArray =
        ///[
        ///];
        ///
        ///floatingMenu.add = function(obj, options)
        ///{
        ///    var name;
        ///    var menu;
        ///
        ///    if (typeof(obj) === &quot;string&quot;)
        ///        name = obj;
        ///    else
        ///        men [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string floating_1_5 {
            get {
                return ResourceManager.GetString("floating_1_5", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap header {
            get {
                object obj = ResourceManager.GetObject("header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap karmarkar_museum {
            get {
                object obj = ResourceManager.GetObject("karmarkar_museum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kashid_beach {
            get {
                object obj = ResourceManager.GetObject("kashid_beach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_map {
            get {
                object obj = ResourceManager.GetObject("location_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_mapLarge {
            get {
                object obj = ResourceManager.GetObject("location_mapLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo_Sagar_Shrushi {
            get {
                object obj = ResourceManager.GetObject("Logo_Sagar_Shrushi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Murud_Janjira {
            get {
                object obj = ResourceManager.GetObject("Murud_Janjira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navi_bar {
            get {
                object obj = ResourceManager.GetObject("navi_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next_icon {
            get {
                object obj = ResourceManager.GetObject("next_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palmtree_icon {
            get {
                object obj = ResourceManager.GetObject("palmtree_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palmtree_iconhighlight {
            get {
                object obj = ResourceManager.GetObject("palmtree_iconhighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_004 {
            get {
                object obj = ResourceManager.GetObject("Picture_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_004small {
            get {
                object obj = ResourceManager.GetObject("Picture_004small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_015 {
            get {
                object obj = ResourceManager.GetObject("Picture_015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_015small {
            get {
                object obj = ResourceManager.GetObject("Picture_015small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_016 {
            get {
                object obj = ResourceManager.GetObject("Picture_016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_016small {
            get {
                object obj = ResourceManager.GetObject("Picture_016small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_017 {
            get {
                object obj = ResourceManager.GetObject("Picture_017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture_017small {
            get {
                object obj = ResourceManager.GetObject("Picture_017small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prev_icon {
            get {
                object obj = ResourceManager.GetObject("prev_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap road {
            get {
                object obj = ResourceManager.GetObject("road", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAM_0627 {
            get {
                object obj = ResourceManager.GetObject("SAM_0627", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAM_0627small {
            get {
                object obj = ResourceManager.GetObject("SAM_0627small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAM_0628 {
            get {
                object obj = ResourceManager.GetObject("SAM_0628", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SAM_0628small {
            get {
                object obj = ResourceManager.GetObject("SAM_0628small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Slide {
            get {
                object obj = ResourceManager.GetObject("Slide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Slidesmall {
            get {
                object obj = ResourceManager.GetObject("Slidesmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snacks {
            get {
                object obj = ResourceManager.GetObject("snacks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__017 {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__017small {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__017small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__025 {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__025small {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__025small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__026 {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__026small {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__026small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__027 {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sony_DSC_S40__Digital_Camera__027small {
            get {
                object obj = ResourceManager.GetObject("Sony_DSC_S40__Digital_Camera__027small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap specialItems {
            get {
                object obj = ResourceManager.GetObject("specialItems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sunset {
            get {
                object obj = ResourceManager.GetObject("sunset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sunset2 {
            get {
                object obj = ResourceManager.GetObject("sunset2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thali {
            get {
                object obj = ResourceManager.GetObject("thali", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap topbar {
            get {
                object obj = ResourceManager.GetObject("topbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap topbar_1 {
            get {
                object obj = ResourceManager.GetObject("topbar_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
